name: Shadow Overlord Bootstrap

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  activate:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/shadow')
    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Run Shadow Overlord
        env:
          GH_TOKEN: ${{ secrets.GITHUB3000_PAT_TOKEN }}
        run: |
          echo "Shadow Overlord Engaged"
          gh api \
            repos/${{ github.repository }}/dispatches \
            -f event_type='shadow_overlord' \
            -f client_payload='{"comment": "${{ github.event.comment.body }}"}'
