name: Autonomous Build & Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build

      - name: Commit build fixes if any
        run: |
          git config user.name "codex-bot"
          git config user.email "codex@3000studios.com"
          git add .
          git commit -m "auto: self-healing build fixes" || true
          git push || true
